# Generated by Django 3.1.7 on 2021-03-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
