# Generated by Django 3.1.7 on 2021-03-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210307_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='diagnosis',
            new_name='notes',
        ),
    ]
